config/routes.rb
Tpna::Application.routes.draw do

  root :to => "home#index"
  devise_for :users
  resources :users



  resources :members do
    collection do 
      post :import
      get :export
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Access to this site is strictly limited to current <a href="http://trinitypark.org/board-and-committees/">TPNA Board Members</a>
    only
  </small>
  <nav>
    <ul>
      <li> <a href="http://trinitypark.org/">Trinity Park Neighborhood Association</a> Durham, NC</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
		<%= link_to "TPNA Membership", root_path, id: "logo" %>
		<nav>
	  	<ul class="nav pull-right">
		  <% if user_signed_in? %>
		  	<li>
		  	<%= link_to 'Members', members_path %>
		  	</li>
		  	<li id="fat-menu" class="dropdown">
        	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Settings <b class="caret"></b></a>
				  <ul class="dropdown-menu">
	          <li><%= link_to 'Profile', edit_user_registration_path %></li>
	          <li class="divider"></li>
	          <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
	        </ul>
    		</li>
		   <% if current_user.has_role? :admin %>
		    <li><%= link_to 'Admin', users_path %></li>
		  <% end %>
		<% else %>
		  <li><%= link_to 'Sign in', new_user_session_path %></li>
	  <% end %>
		</ul>
		</nav>
 		</div>
 	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Trinity Park Neighborhood Association Membership List" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
	<%= render 'layouts/header' %>
  	<div class="container">
      <% flash.each do |key, value| %>
      	<%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>