config/routes.rb
Tpna::Application.routes.draw do

  root :to => "home#index"
  devise_for :users
  resources :users



  resources :members do
    collection do 
      post :import
      get :export
    end
  end

end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  street_address    :string(255)
#  member_since      :date
#  last_payment_date :date
#  amt               :integer
#  paid_thru         :date
#  email             :string(255)
#  phone             :string(255)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Member < ActiveRecord::Base
  paginates_per 50
  # attr_accessible :name, :street_address, :member_since, :last_payment_date, :amt, :paid_thru, :email, :phone, :notes

  validates :name, presence: true
  validates :street_address, presence: true, uniqueness: { case_sensitive: false }

  scope :matching, lambda {|query| where('name ILIKE ? OR street_address ILIKE ?', "%#{query}%", "%#{query}%")}
  scope :renewal_matching, lambda {|renewal_query_start, renewal_query_end| where('paid_thru BETWEEN ? and ?', "%#{renewal_query_start}%", "%#{renewal_query_end}%")}

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |member|
        csv << member.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      member = find_by_id(row["id"]) || find_by_id(row["Id"]) || new 
      member.attributes = rehash_keys(row)

      member.save!
    end
  end

  def self.rehash_keys(row)
    row_hash = row.to_hash
    new_keys_hash = {}
    row_hash.each do |old_key,old_value|
      new_keys_hash[old_key.downcase.gsub(/[^a-z]/, '_')] = old_value
    end
    new_keys_hash
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end


  def self.search(query)
    if query.present?
      matching(query)
    else
      where(nil)
    end
  end

  def self.renewal_between(start_date, end_date)
    if [start_date, end_date].all?(&:present?)
      renewal_matching(start_date, end_date)
    elsif start_date.present?
      where("paid_thru >= ?", start_date)
    elsif end_date.present?
      where("paid_thru <= ?", end_date)
    else
      where(nil)
    end
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  check_authorization

  helper_method :sort_column, :sort_direction

  def index
    authorize! :read, @user, :message => 'Not authorized to read.'
    @members = filtered_paginated_members
    respond_to do |format|
        format.html
        format.js
      end
  end

  def export
    authorize! :read, @user, :message => 'Not authorized to read.'
    @members = filtered_members
    respond_to do |format|
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"#{download_filename}\""
        headers['Content-Type'] ||= 'text/csv'
        column_names = Member.column_names
        csv_data = CSV.generate do |csv|
          csv <<  column_names
          @members.each do |member|
            csv << member.attributes.values_at(*column_names) 
          end
        end
        send_data csv_data, type: 'text/csv; charset=utf-8; header=present', disposition: "attachment; filename=#{download_filename}"
      end
    end
  end

  def new
    authorize! :create, @user, :message => 'Not authorized to create.'
    @member = Member.new
  end

  def create
    authorize! :create, @user, :message => 'Not authorized to create.'
      @member = Member.new(member_params)
      if @member.save
        redirect_to members_path, :notice => "Member created."
      else
        render 'new'
      end
  end

  def edit
    authorize! :read, @user, :message => 'Not authorized to view details.'
    @member = Member.find(params[:id])
  end

  def update
    authorize! :update, @user, :message => 'Not authorized to edit.'
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to members_path, :notice => "Member updated."
    else
      render 'edit'
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized to delete.'
    @member = Member.find(params[:id])
    @member.destroy

    redirect_to members_path, :notice => "Member deleted."
  end

  def import
    authorize! :update, @user, :message => 'Not authorized to edit.'
    Member.import(params[:file])
    redirect_to root_url, notice: "Members imported."
  end

  private

  def sort_column
    Member.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def download_filename
    ['tpna-members', params[:search], Time.current.to_s].compact.join('-') + '.csv'
  end

  def filtered_members
    Member.search(params[:search]).renewal_between(params[:renewal_date_start], params[:renewal_date_end]).order(sort_column + " " + sort_direction)
  end

  def filtered_paginated_members
    filtered_members.page(params[:page])
  end

  def member_params
    params.require(:member).permit(:name, :street_address, :member_since, :last_payment_date, :amt, :paid_thru, :email, :phone, :notes)
  end
end

app/helpers/members_helper.rb
module MembersHelper
  def link_to_google_maps(address)
    street_address = address.partition(',')[0]
    query = u("#{street_address}, Durham, NC")
    link_to address, "http://maps.google.com/?q=#{query}", target: "_blank"
  end
end

app/views/members/_fields.html.erb
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :street_address, "Street Address" %>
<%= f.text_field :street_address %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :phone %>
<%= f.text_field :phone %>

<%= f.label :member_since %>
<%= f.date_field :member_since %>


<%= f.label :last_payment_date, "Last Payment" %>
<%= f.date_field :last_payment_date %>

<%= f.label :amt, "Amount" %>
<%= f.text_field :amt %>

<%= f.label :paid_thru, "Expires" %>
<%= f.date_field :paid_thru %>

<%= f.label :notes %>
<%= f.text_field :notes %>

app/views/members/_members.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= sortable "id", "ID" %></th>
      <th><%= sortable "name" %></th>
      <th><%= sortable "street_address", "Street Address" %></th>
      <th><%= sortable "email" %></th>
      <th><%= sortable "last_payment_date", "Last Payment" %></th>
      <th><%= sortable "amt", "Amount" %></th>
      <th><%= sortable "paid_thru", "For Renewal On" %></th>
      <th><%= sortable "notes", "Notes" %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.id %></td>
        <td><%= link_to member.name, edit_member_path(member) %></td>
        <td><%= link_to_google_maps member.street_address %></td>
        <td><%= mail_to member.email %></td>
        <td><%= member.last_payment_date %></td>
        <td><%= number_to_currency member.amt %></td>
        <td><%= member.paid_thru %></td>
        <td><%= member.notes %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @members %>

app/views/members/edit.html.erb
<% provide(:title, "Edit Member") %> 
<h1>Update member information</h1>

<div class="span2 offset3">
  <%= button_to "Delete this Member", member_path(@member), method: :delete, data: { confirm: "Are you sure you want to delete this member?" }, class: "btn btn-danger" %>
</div>

<div class="row">
  <div class="span6 offset3">
	<%= form_for(@member) do |f| %>
  	<%= render 'shared/error_messages', object: f.object %>
    <%= render 'fields', f: f %>
    <%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>
	</div>
</div>

app/views/members/index.html.erb
<% provide(:title, "Member List") %>
<h1>Member List</h1>

<%= form_tag members_path, :method => 'get', :id => "members_search", :class => 'form-search' do %>
  <div class="row">
    <div class="span6">
      <%= text_field_tag :search, params[:search], placeholder: 'Start typing name or address to search...' %>
    </div>
		<div class="span2">
			<%= date_field_tag :renewal_date_start, params[:renewal_date_start] %>
      <span class="help-block">Renewal Date (Start)</span>
		</div>
		<div class="span2">
			<%= date_field_tag :renewal_date_end, params[:renewal_date_end] %>
      <span class="help-block">Renewal Date (End)</span>
		</div>
		<div class="span2">
      <%= link_to export_members_path(format: "csv"), :class => 'btn btn-block', :id => 'members-list-download' do %>
        Export This List
        <%= icon('download') %>
      <%- end %>
    </div>
  </div>
  <div id="members" class="members-table"><%= render 'members' %></div>
<% end %>

app/views/members/index.js.erb
$("#members").html("<%= escape_javascript(render("members")) %>");

app/views/members/new.html.erb
<% provide(:title, "Add Member") %> 
<h1>Add new member</h1>

<div class="row">
  <div class="span6 offset3">
	<%= form_for(@member) do |f| %>
  	<%= render 'shared/error_messages', object: f.object %>
    <%= render 'fields', f: f %>
    <%= f.submit "Create member", class: "btn btn-primary" %>
<% end %>
	</div>
</div>